[build]
  base = "pc/frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.21.1"
  VITE_API_BASE = "https://digiscribe-backend-app-24d016f3a2b4.herokuapp.com"
